### ISSUE TITLE
♻️ [REFACTOR] DTO 양식 통일

### ISSUE THREAD

**Issue by oxdjww** [Soongsil-CoffeeChat/COGO-DEV-server#102]
# Title
- DTO 양식 통일

# Content
- DTO 양식 통일

# TODO
- [x] DTO 양식 통일
- [x] 전체 코드 포맷팅
- [x] 불필요 import 제거
